### ISSUE TITLE
Update python API to new version

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/elastictube1d#10]
The [python version of the elastic tube](https://github.com/precice/elastictube1d/tree/master/PythonTube) uses `PySolverInterface`. We should update to using `precice`. See [Changelog v1.4.0](https://github.com/precice/precice/blob/develop/CHANGELOG.md).

**Comment by micheltakken** [comment]
I'm working on this as well

**Comment by richahert** [comment]
I just changed the API calls and module name. Didn't figure out how to make a pull request yet but I'll do it when I find out. Here are the changed solver files in the meantime:
[updates.zip](https://github.com/precice/elastictube1d/files/3058295/updates.zip)

**Comment by BenjaminRodenberg** [comment]
@richahert How to create a pull request from a fork is explained [here](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork). You can also give @micheltakken developer access to your fork, then you can work on this together.

@micheltakken Please add a link to the branch/fork where you are working on this issue?

**Comment by BenjaminRodenberg** [comment]
PR #11 updates the API version. As soon as it is merged, we can close this issue.
