### ISSUE TITLE
C++ version crashes (coupling residual equals zero)

### ISSUE THREAD

**Issue by Eder-K** [precice/elastictube1d#33]
Recently, [the elastictube1d-C++ systemtest has started failing during cron jobs on the develop branch](https://travis-ci.org/github/precice/systemtests/jobs/706169757).

Looking at the Fluid and Structure log one can observe the following:
in Fluid.log:
```
...
(0) 11:36:25 [impl::SolverInterfaceImpl]:413 in advance: [0mit 4 of 40 | dt# 2 | t 0.01 of 1 | dt 0.01 | max dt 0.01 | ongoing yes | dt complete no | read-iteration-checkpoint | 
Nonlinear Solver break, iterations: 3, residual norm: 6.494819e-16
(0) 11:36:25 [com::SocketCommunication]:722 in receive: [31mERROR: [0mReceive failed: read: End of file
```

in Solid.log:
```
...
(0) 11:36:25 [cplscheme::BaseCouplingScheme]:566 in measureConvergence: [0mAll converged
(0) 11:36:25 [acceleration::BaseQNAcceleration]:199 in updateDifferenceMatrices: [31mERROR: [0mThe coupling residual equals zero. There is probably something wrong in your adapter. Maybe you always write the same data or you call advance without providing new data first or you do not use available read data.
```

Below are the full logfiles that get generated until the error:
[Fluid.log](https://github.com/precice/elastictube1d/files/4896578/Fluid.log)
[Structure.log](https://github.com/precice/elastictube1d/files/4896579/Structure.log)
[precice-STRUCTURE-convergence.log](https://github.com/precice/elastictube1d/files/4896582/precice-STRUCTURE-convergence.log)
[precice-STRUCTURE-iterations.log](https://github.com/precice/elastictube1d/files/4896583/precice-STRUCTURE-iterations.log)
[precice-FLUID-iterations.log](https://github.com/precice/elastictube1d/files/4896584/precice-FLUID-iterations.log)

The test is running on the precice baseimage "precice-ubuntu1604.home-develop" and uses the develop version of the elastictube tutorial.

**Comment by uekerman** [comment]
We recently added this check to preCICE: https://github.com/precice/precice/pull/787
My best guess currently is that the solid solver actually does something wrong and that the error is a true positive.
I'll have a look.
Good that the system tests catch such problems :+1:

**Comment by uekerman** [comment]
Was indeed a "bug" in preCICE -- a too strict check. https://github.com/precice/precice/pull/793 relaxes the check to a warning. Then, the elastic tube should work again.

**Comment by uekerman** [comment]
Should be fixed. Please close if the system tests work again.

**Comment by Eder-K** [comment]
[The test works once again](https://travis-ci.org/github/precice/systemtests/jobs/706972631), thanks for the quick fix.
