### ISSUE TITLE
sign in residual for convective term

### ISSUE THREAD

**Issue by davydden** [precice/elastictube1d#35]
I was looking into this 1D case and noticed that in both python and C++ code in preCICe the signs in descritization of convective term for `a[i+1] p[i+1]` and `a[i+1] p[i]` are the same, see https://github.com/precice/elastictube1d/blob/master/cxx/FluidSolver_Serial/fluid_nl.cpp#L80-L84

Given that this comes from `a_{i+1/2} [p_{i+1} - p_{i}]`, see (13b) in Degroot 2008, I would expect the signs in C++ code to be opposite for terms `a_{i+1}p_{i}` and `a_{i-1} p_{i}`.

**Comment by uekerman** [comment]
I just checked the terms again. I think you are right. Those signs are so easy to mess up. Good catch!

https://github.com/precice/elastictube1d/blob/5b1294c684b27d04c45a83243fae222b2dd3b013/cxx/FluidSolver_Serial/fluid_nl.cpp#L84

It should be:

```c++
+ 0.25 * crossSectionLength[i - 1] * pressure[i - 1] 
+ 0.25 * crossSectionLength[i] * pressure[i - 1] 
- 0.25 * crossSectionLength[i - 1] * pressure[i] //currently "+"
+ 0.25 * crossSectionLength[i + 1] * pressure[i] //currently "-"
- 0.25 * crossSectionLength[i] * pressure[i + 1] 
- 0.25 * crossSectionLength[i + 1] * pressure[i + 1] 
```

Same for the Python code (which historically was just a language copy from C++) and the parallel fluid code.

Do you want to open a PR?

**Comment by davydden** [comment]
> Do you want to open a PR?

sure, will do.
